import React from "react";
import Link from "next/link";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/homescreen" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Homescreen
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/categoryscreendefaultfilter" style={{ color: "#87CEFA", textDecoration: "none" }}>
            CategoryScreenDefaultFilter
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/detaillistingscreen" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DetailListingScreen
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/aboutpage" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Aboutpage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/hubungikami" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HubungiKami
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/snk" style={{ color: "#87CEFA", textDecoration: "none" }}>
            SnK
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
